from __future__ import annotations
from typing import Optional, Iterable, Dict, Any, Union, Protocol, List

from arduino_colab_kernel.board.board import Board

class Backend(Protocol):
    """Jednotné Board-first rozhraní – žádné duplikace konfigurace mimo Board."""
    # --- build & deploy ---
    def compile(self, board: Board, sketch_source: str,
                extra_args: Optional[Iterable[str]] = None) -> Dict[str, Any]: ...
    def upload(self, board: Board, sketch_source: str,
               extra_args: Optional[Iterable[str]] = None) -> Dict[str, Any]: ...
    # --- serial io ---
    def open_serial(self, board: Board) -> None: ...
    def close_serial(self, board: Board) -> None: ...
    def read_serial(self, board: Board, size: int = -1) -> bytes: ...
    def readlines_serial(self, board: Board, size: int = 1) -> List[str]: ...
    def write_serial(self, board: Board, data: Union[bytes, str], append_newline: bool = True) -> int: ...